/* Translations for the Commercial Offer document generator.
 * Language keys must match across DOC_STRINGS and LATE_PAYMENT: EN DE RU CZ FR ES PL HU IT EL.
 * Loaded before deal_commercial_offer.js via init.php.
 */

/* jshint quotmark: false */
window.OFFER_DOC_STRINGS = {
    EN: {
        docTitle:   'Commercial Offer',
        offerLabel: 'No. ',
        validUntil: 'Valid until: ',
        seller:     'Seller',
        buyer:      'Buyer',
        attn:       'Attn.: ',
        delivery:   'Delivery: ',
        tel:        'Tel.: ',
        vatNo:      'VAT No.: ',
        colNo:      'No.',
        colDesc:    'Description',
        colQty:     'Qty',
        colPrice:   'Unit Price',
        colVat:     'VAT',
        colTotal:   'Total',
        subtotal:   'Subtotal (excl. VAT)',
        vatZero:    'VAT (0%)',
        total:      'TOTAL',
        techSpecs:  'Technical Specifications',
        physParams: 'Physical Parameters',
        extDim:     'External dimensions (W×D×H)',
        intDim:     'Internal dimensions (W×D×H)',
        netWeight:  'Net weight',
        vatNote:    'VAT 0% – Reverse charge mechanism applies (Article 196, Council Directive 2006/112/EC)',
        printSave:  'Print / Save PDF'
    },
    DE: {
        docTitle:   'Angebot',
        offerLabel: 'Nr. ',
        validUntil: 'Gültig bis: ',
        seller:     'Verkäufer',
        buyer:      'Käufer',
        attn:       'z. H.: ',
        delivery:   'Lieferadresse: ',
        tel:        'Tel.: ',
        vatNo:      'USt-IdNr.: ',
        colNo:      'Nr.',
        colDesc:    'Bezeichnung',
        colQty:     'Menge',
        colPrice:   'Stückpreis',
        colVat:     'MwSt.',
        colTotal:   'Gesamt',
        subtotal:   'Zwischensumme (ohne MwSt.)',
        vatZero:    'MwSt. (0%)',
        total:      'GESAMT',
        techSpecs:  'Technische Spezifikationen',
        physParams: 'Physikalische Parameter',
        extDim:     'Außenmaße (B×T×H)',
        intDim:     'Innenmaße (B×T×H)',
        netWeight:  'Nettogewicht',
        vatNote:    'MwSt. 0% – Reverse-Charge-Verfahren gemäß Art. 196 der Richtlinie 2006/112/EG',
        printSave:  'Drucken / Als PDF speichern'
    },
    RU: {
        docTitle:   'Коммерческое предложение',
        offerLabel: '№ ',
        validUntil: 'Действительно до: ',
        seller:     'Продавец',
        buyer:      'Покупатель',
        attn:       'Вниманию: ',
        delivery:   'Адрес доставки: ',
        tel:        'Тел.: ',
        vatNo:      'НДС №: ',
        colNo:      '№',
        colDesc:    'Наименование',
        colQty:     'Кол-во',
        colPrice:   'Цена за ед.',
        colVat:     'НДС',
        colTotal:   'Сумма',
        subtotal:   'Итого (без НДС)',
        vatZero:    'НДС (0%)',
        total:      'ИТОГО',
        techSpecs:  'Технические характеристики',
        physParams: 'Физические параметры',
        extDim:     'Внешние размеры (Ш×Г×В)',
        intDim:     'Внутренние размеры (Ш×Г×В)',
        netWeight:  'Вес нетто',
        vatNote:    'НДС 0% – механизм обратного начисления (Ст. 196, Директива 2006/112/EC)',
        printSave:  'Печать / Сохранить PDF'
    },
    CZ: {
        docTitle:   'Cenová nabídka',
        offerLabel: 'č. ',
        validUntil: 'Platnost do: ',
        seller:     'Prodejce',
        buyer:      'Kupující',
        attn:       'K rukám: ',
        delivery:   'Adresa doručení: ',
        tel:        'Tel.: ',
        vatNo:      'DIČ kupujícího: ',
        colNo:      'č.',
        colDesc:    'Popis',
        colQty:     'Množství',
        colPrice:   'Jednotková cena',
        colVat:     'DPH',
        colTotal:   'Celkem',
        subtotal:   'Mezisoučet (bez DPH)',
        vatZero:    'DPH (0%)',
        total:      'CELKEM',
        techSpecs:  'Technická specifikace',
        physParams: 'Fyzické parametry',
        extDim:     'Vnější rozměry (Š×H×V)',
        intDim:     'Vnitřní rozměry (Š×H×V)',
        netWeight:  'Čistá hmotnost',
        vatNote:    'DPH 0% – přenesení daňové povinnosti (čl. 196 Směrnice Rady 2006/112/ES)',
        printSave:  'Tisk / Uložit jako PDF'
    },
    FR: {
        docTitle:   'Offre commerciale',
        offerLabel: 'N° ',
        validUntil: "Valable jusqu'au : ",
        seller:     'Vendeur',
        buyer:      'Acheteur',
        attn:       "À l'attention de : ",
        delivery:   'Adresse de livraison : ',
        tel:        'Tél. : ',
        vatNo:      'N° TVA : ',
        colNo:      'N°',
        colDesc:    'Désignation',
        colQty:     'Qté',
        colPrice:   'Prix unitaire',
        colVat:     'TVA',
        colTotal:   'Total',
        subtotal:   'Sous-total (HT)',
        vatZero:    'TVA (0%)',
        total:      'TOTAL',
        techSpecs:  'Spécifications techniques',
        physParams: 'Paramètres physiques',
        extDim:     'Dimensions extérieures (L×P×H)',
        intDim:     'Dimensions intérieures (L×P×H)',
        netWeight:  'Poids net',
        vatNote:    'TVA 0% – autoliquidation (article 196, directive 2006/112/CE)',
        printSave:  'Imprimer / Enregistrer en PDF'
    },
    ES: {
        docTitle:   'Oferta comercial',
        offerLabel: 'N.º ',
        validUntil: 'Válida hasta: ',
        seller:     'Vendedor',
        buyer:      'Comprador',
        attn:       'A/A: ',
        delivery:   'Dirección de entrega: ',
        tel:        'Tel.: ',
        vatNo:      'N.º IVA: ',
        colNo:      'N.º',
        colDesc:    'Descripción',
        colQty:     'Cant.',
        colPrice:   'Precio unitario',
        colVat:     'IVA',
        colTotal:   'Total',
        subtotal:   'Subtotal (sin IVA)',
        vatZero:    'IVA (0%)',
        total:      'TOTAL',
        techSpecs:  'Especificaciones técnicas',
        physParams: 'Parámetros físicos',
        extDim:     'Dimensiones externas (An×Pr×Al)',
        intDim:     'Dimensiones internas (An×Pr×Al)',
        netWeight:  'Peso neto',
        vatNote:    'IVA 0% – inversión del sujeto pasivo (art. 196, Directiva 2006/112/CE)',
        printSave:  'Imprimir / Guardar como PDF'
    },
    PL: {
        docTitle:   'Oferta handlowa',
        offerLabel: 'Nr ',
        validUntil: 'Ważna do: ',
        seller:     'Sprzedawca',
        buyer:      'Kupujący',
        attn:       'Do rąk: ',
        delivery:   'Adres dostawy: ',
        tel:        'Tel.: ',
        vatNo:      'Nr VAT: ',
        colNo:      'Lp.',
        colDesc:    'Opis',
        colQty:     'Ilość',
        colPrice:   'Cena jedn.',
        colVat:     'VAT',
        colTotal:   'Wartość',
        subtotal:   'Suma netto',
        vatZero:    'VAT (0%)',
        total:      'RAZEM',
        techSpecs:  'Specyfikacja techniczna',
        physParams: 'Parametry fizyczne',
        extDim:     'Wymiary zewnętrzne (Sz×Gł×Wys.)',
        intDim:     'Wymiary wewnętrzne (Sz×Gł×Wys.)',
        netWeight:  'Waga netto',
        vatNote:    'VAT 0% – odwrotne obciążenie (art. 196 dyrektywy 2006/112/WE)',
        printSave:  'Drukuj / Zapisz jako PDF'
    },
    HU: {
        docTitle:   'Kereskedelmi ajánlat',
        offerLabel: 'Sz. ',
        validUntil: 'Érvényes: ',
        seller:     'Eladó',
        buyer:      'Vevő',
        attn:       'Címzett: ',
        delivery:   'Szállítási cím: ',
        tel:        'Tel.: ',
        vatNo:      'Adószám: ',
        colNo:      'Ssz.',
        colDesc:    'Megnevezés',
        colQty:     'Menny.',
        colPrice:   'Egységár',
        colVat:     'ÁFA',
        colTotal:   'Összesen',
        subtotal:   'Részösszeg (ÁFA nélkül)',
        vatZero:    'ÁFA (0%)',
        total:      'ÖSSZESEN',
        techSpecs:  'Műszaki specifikáció',
        physParams: 'Fizikai paraméterek',
        extDim:     'Külső méretek (Sz×Mé×M)',
        intDim:     'Belső méretek (Sz×Mé×M)',
        netWeight:  'Nettó tömeg',
        vatNote:    'ÁFA 0% – fordított adózás (196. cikk, 2006/112/EK irányelv)',
        printSave:  'Nyomtatás / Mentés PDF-ként'
    },
    IT: {
        docTitle:   'Offerta commerciale',
        offerLabel: 'N. ',
        validUntil: 'Valida fino al: ',
        seller:     'Venditore',
        buyer:      'Acquirente',
        attn:       "All'attenzione di: ",
        delivery:   'Indirizzo di consegna: ',
        tel:        'Tel.: ',
        vatNo:      'P.IVA: ',
        colNo:      'N.',
        colDesc:    'Descrizione',
        colQty:     'Q.tà',
        colPrice:   'Prezzo unitario',
        colVat:     'IVA',
        colTotal:   'Totale',
        subtotal:   'Totale parziale (IVA esclusa)',
        vatZero:    'IVA (0%)',
        total:      'TOTALE',
        techSpecs:  'Specifiche tecniche',
        physParams: 'Parametri fisici',
        extDim:     'Dimensioni esterne (L×P×A)',
        intDim:     'Dimensioni interne (L×P×A)',
        netWeight:  'Peso netto',
        vatNote:    'IVA 0% – inversione contabile (art. 196, direttiva 2006/112/CE)',
        printSave:  'Stampa / Salva come PDF'
    },
    EL: {
        docTitle:   'Εμπορική προσφορά',
        offerLabel: 'Αρ. ',
        validUntil: 'Ισχύει έως: ',
        seller:     'Πωλητής',
        buyer:      'Αγοραστής',
        attn:       'Υπόψη: ',
        delivery:   'Διεύθυνση παράδοσης: ',
        tel:        'Τηλ.: ',
        vatNo:      'ΑΦΜ: ',
        colNo:      'Α/Α',
        colDesc:    'Περιγραφή',
        colQty:     'Ποσ.',
        colPrice:   'Τιμή μονάδος',
        colVat:     'ΦΠΑ',
        colTotal:   'Σύνολο',
        subtotal:   'Υποσύνολο (χωρίς ΦΠΑ)',
        vatZero:    'ΦΠΑ (0%)',
        total:      'ΣΥΝΟΛΟ',
        techSpecs:  'Τεχνικές προδιαγραφές',
        physParams: 'Φυσικές παράμετροι',
        extDim:     'Εξωτερικές διαστάσεις (Π×Β×Υ)',
        intDim:     'Εσωτερικές διαστάσεις (Π×Β×Υ)',
        netWeight:  'Καθαρό βάρος',
        vatNote:    'ΦΠΑ 0% – αντιστροφή υποχρέωσης (άρθρο 196, οδηγία 2006/112/ΕΚ)',
        printSave:  'Εκτύπωση / Αποθήκευση ως PDF'
    }
};

window.OFFER_LATE_PAYMENT = {
    EN: {
        title: 'Late Payment Clause',
        text:  'In case of payment delay exceeding 20 working days, the Buyer is obliged, in accordance with EU Directive 2011/7/EU, to pay late interest at the base rate of the European Central Bank plus 8 percentage points per annum, calculated daily from the due date until the date of actual payment. Additionally, the Buyer must pay a fixed compensation of 40 EUR to cover debt collection costs.'
    },
    DE: {
        title: 'Klausel zum Zahlungsverzug',
        text:  'Bei Zahlungsverzug von mehr als 20 Werktagen ist der Käufer verpflichtet, gemäß EU-Richtlinie 2011/7/EU Verzugszinsen in Höhe des Basiszinssatzes der Europäischen Zentralbank zuzüglich 8 Prozentpunkte Jahreszinsen zu zahlen, die täglich ab dem Tag des Verzugs bis zum Tag der tatsächlichen Zahlung berechnet werden. Darüber hinaus ist der Käufer verpflichtet, eine pauschale Entschädigung in Höhe von 40 EUR zur Deckung der Inkassokosten zu zahlen.'
    },
    RU: {
        title: 'Условие о просрочке платежа',
        text:  'В случае нарушения сроков оплаты более чем на 20 рабочих дней, Покупатель обязан в соответствии с Директивой ЕС 2011/7/EU уплатить проценты за просрочку в размере базовой ставки ЕЦБ плюс 8 процентных пунктов годовых, начисляемых ежедневно с даты просрочки. Дополнительно Покупатель обязан оплатить фиксированную компенсацию 40 EUR.'
    },
    CZ: {
        title: 'Doložka o prodlení s platbou',
        text:  'V případě prodlení s platbou delším než 20 pracovních dní je Kupující povinen podle Směrnice EU 2011/7/EU zaplatit úroky z prodlení ve výši základní sazby Evropské centrální banky zvýšené o 8 procentních bodů ročně, počítané denně od data vzniku prodlení až do data skutečné úhrady. Kromě toho je Kupující povinen uhradit pevnou náhradu ve výši 40 EUR na pokrytí nákladů spojených s vymáháním pohledávky.'
    },
    FR: {
        title: 'Clause de retard de paiement',
        text:  "En cas de retard du paiement de plus de 20 jours ouvrables, l'Acheteur est tenu, conformément à la Directive UE 2011/7/UE, de payer des intérêts de retard à hauteur du taux de base de la Banque Centrale Européenne majoré de 8 points de pourcentage par an, calculés quotidiennement à compter de la date du retard jusqu'à la date du paiement effectif. En outre, l'acheteur est tenu de payer une indemnié forfaitaire de 40 EUR."
    },
    ES: {
        title: 'Cláusula de mora en el pago',
        text:  'En caso de incumplimiento de los plazos de pago por más de 20 días hábiles, el Comprador estará obligado, de conformidad con la Directiva de la UE 2011/7/UE, a abonar intereses de demora equivalentes al tipo de interés básico del Banco Central Europeo más 8 puntos porcentuales anuales, calculados diariamente desde la fecha de vencimiento hasta la fecha del pago efectivo.'
    },
    PL: {
        title: 'Klauzula o opóżnieniu płatności',
        text:  'W przypadku opóźnienia w płatności przekraczającego 20 dni roboczych, Kupujący zobowiązany jest, zgodnie z Dyrektywą UE 2011/7/UE, do zapłaty odsetek za zwłokę w wysokości stopy bazowej Europejskiego Banku Centralnego powiększonej o 8 punktów procentowych rocznie, naliczanych codziennie od dnia opóźnienia do dnia faktycznej zapłaty. Dodatkowo Kupujący zobowiązany jest do zapłaty kwoty w wysokości 40 EUR na pokrycie kosztów windykacji.'
    },
    HU: {
        title: 'Késedelmes fizetésre vonatkozó záradék',
        text:  'Ha a fizetési határidő több mint 20 munkanappal túl lépődik, a Vevő köteles az EU 2011/7/EU irányvonalának megfelelően késedelmi kamatot fizetni az Európai Központi Bank alapkamata plusz 8 százalékpont mértékében, amelyet naponta számítanak fel. Ezen felül a Vevő köteles 40 euró összegű fix kártérítést fizetni a követelés behajtásával kapcsolatos költségek fedezésére.'
    },
    IT: {
        title: 'Clausola di ritardo nel pagamento',
        text:  "In caso di ritardo nel pagamento superiore a 20 giorni lavorativi, l'Acquirente è tenuto, conformemente alla Direttiva UE 2011/7/UE, a pagare gli interessi di mora pari al tasso base della Banca Centrale Europea più 8 punti percentuali annui, calcolati giornalmente dalla data di scadenza del pagamento fino alla data effettiva di saldo. Inoltre, l'Acquirente è obbligato a corrispondere un'indemnià forfettaria di 40 EUR a copertura delle spese di recupero crediti."
    },
    EL: {
        title: 'Ρήτρα καθυστέρησης πληρωμής',
        text:  'Σε περίπτωση καθυστέρησης πληρωμής άνω των 20 εργάσιμων ημερών, ο Αγοραστής υποχρεούται, σύμφωνα με την Οδηγία 2011/7/ΕΕ, να καταβάλλει τόκους καθυστέρησης ισοδύναμους με το βασικό επιτόκιο της ΕΚΤ συν επιπλέον 8 ετήσιες ποσοστιαίες μονάδες, υπολογιζόμενους ημερησίως. Επιπλέον, ο Αγοραστής οφείλει να πληρώσει σταθερή αποζημίωση 40 ευρώ για την κάλυψη εξόδων είσπραξης.'
    }
};
